name: Purge deprecated workflow runs
description: >-
  Delete github workflow runs that don't have a corresponding workflow (anymore) from the
  current repository.
author: hanseartic
inputs:
  token:
    description: The token to authenticate on the repository
    required: false
    default: ${{ github.token }}
  remove-obsolete:
    description: Remove obsolete (there is no definition anymore) workflow runs
    required: false
    default: true
  remove-cancelled:
    description: Remove cancelled workflow runs
    required: false
    default: false
  remove-failed:
    description: Remove failed workflow runs
    required: false
    default: false
  remove-skipped:
    description: Remove skipped workflow runs
    required: false
    default: false
runs:
  using: node20
  main: index.js
branding:
  icon: trash-2
  color: yellow
