name: Remove obsolete github workflow runs
description: >-
  Delete github workflow runs for workflows that have been removed from the
  current repository.
author: hanseartic
inputs:
  token:
    description: The token to authenticate on the repository
    required: true
    default: '${{ github.token }}'
runs:
  using: node16
  main: dist/index.js
branding:
  icon: trash-2
  color: yellow
