name: Purge workflow runs
on:
  workflow_dispatch:
  schedule:
    - cron: '54 0 * * 0'
jobs:
  purge_obsolete_workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: otto-de/purge-deprecated-workflow-runs@v3.0.0
        with:
          token: ${{ github.token }}
          remove-obsolete: true
      - uses: otto-de/purge-deprecated-workflow-runs@v3.0.0
        with:
          token: ${{ github.token }}
          remove-older-than: 30d
