name: Purge workflow runs
on:
  workflow_dispatch:
  schedule:
    - cron: '54 0 * * 0'
jobs:
  purge_obsolete_workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: otto-de/purge-deprecated-workflow-runs@v2
        with:
          token: ${{ github.token }}
      - uses: otto-de/purge-deprecated-workflow-runs@v2
        with:
          token: ${{ github.token }}
          remove-obsolete: false
          remove-older-than: 30d
